name: Merle verreist
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Merle verreist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010201'
    - '#bebcb8'
    - '#918b7c'
    - '#475b65'
    - '#a31e3a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
